using System;
using System.Collections.Generic;

namespace Mill_Project.Models
{
    public partial class en_item_tbl
    {
        public string en_item_key { get; set; }
        public string en_item_sdesc { get; set; }
        public string en_item_desc { get; set; }
        public int en_item_cmth { get; set; }
        public string en_phfmt_key { get; set; }
        public short en_item_shelf { get; set; }
        public double en_item_lead { get; set; }
        public string en_mohcd_key { get; set; }
        public string uom_key { get; set; }
        public string en_item_abcc { get; set; }
        public string en_srce_key { get; set; }
        public string en_class_key { get; set; }
        public string en_comcd_key { get; set; }
        public short en_item_ndysp { get; set; }
        public double en_item_sstk { get; set; }
        public double en_item_minoq { get; set; }
        public int en_item_ropt { get; set; }
        public string en_stats_key { get; set; }
        public Nullable<System.DateTime> en_item_lscdt { get; set; }
        public int en_item_pmcd { get; set; }
        public string en_type_key { get; set; }
        public string en_itgrp_key { get; set; }
        public string en_itcat_key { get; set; }
        public string en_item_trdnm { get; set; }
        public string en_ituse_key { get; set; }
        public string en_item_trdmk { get; set; }
        public string en_item_orgin { get; set; }
        public string en_audt_key { get; set; }
        public string sa_user_key { get; set; }
        public string en_item_cmnts { get; set; }
        public System.DateTime en_item_crtdt { get; set; }
        public System.DateTime en_item_chgdt { get; set; }
        public string en_subst_key { get; set; }
        public string en_item_duom { get; set; }
        public double en_item_wgt { get; set; }
        public string en_item_wuom { get; set; }
        public int en_item_cnfgf { get; set; }
        public string en_item_ssds { get; set; }
        public Nullable<System.DateTime> en_ssds_date { get; set; }
        public string en_item_ssby { get; set; }
        public Nullable<System.DateTime> en_ssby_date { get; set; }
        public string en_item_revno { get; set; }
        public string en_item_drwsz { get; set; }
        public string en_item_drwno { get; set; }
        public string ec_hdr_key { get; set; }
        public string en_item_srlf { get; set; }
        public string en_catlg_key { get; set; }
        public double en_item_wdth { get; set; }
        public double en_item_hght { get; set; }
        public double en_item_dpth { get; set; }
        public string en_gtech_key { get; set; }
        public string en_item_dmuom { get; set; }
        public string en_item_chem { get; set; }
        public string en_phyfm_key { get; set; }
        public double en_item_spgvt { get; set; }
        public string en_item_cert { get; set; }
        public double en_item_yldf { get; set; }
        public string en_item_lot { get; set; }
        public string en_item_msds { get; set; }
        public string en_item_clrno { get; set; }
        public string en_item_cas { get; set; }
        public string en_item_ca2 { get; set; }
        public string en_item_dotpg { get; set; }
        public string en_item_hzpdo { get; set; }
        public string en_item_hzpun { get; set; }
        public double en_item_cpk { get; set; }
        public short en_item_lvlcd { get; set; }
        public short en_item_allocf { get; set; }
        public short en_item_pickf { get; set; }
        public short en_item_bkflf { get; set; }
        public short en_item_lotalcf { get; set; }
        public short en_item_sopolicy { get; set; }
        public short en_item_wtpolicy { get; set; }
        public short en_item_wopolicy { get; set; }
        public string en_uomgrp_key { get; set; }
        public Nullable<short> en_item_ffltm { get; set; }
        public Nullable<short> en_item_piktm { get; set; }
        public Nullable<short> en_item_rsrvtm { get; set; }
        public double en_item_pltqt { get; set; }
        public double en_item_vol { get; set; }
        public string en_item_vuom { get; set; }
        public short en_item_actconf { get; set; }
        public short en_item_drctf { get; set; }
        public string en_frtitem_key { get; set; }
        public short en_item_taxf { get; set; }
        public string en_resn_key { get; set; }
        public short en_item_fillattr { get; set; }
        public string en_item_upcean { get; set; }
        public string en_item_scccode { get; set; }
        public string en_item_sccdesc { get; set; }
        public Nullable<short> en_item_mfridlen { get; set; }
        public int en_item_actfillf { get; set; }
        public int en_item_sublotf { get; set; }
        public int en_item_qcsublotf { get; set; }
        public short en_item_hazf { get; set; }
        public short en_item_bkflinf { get; set; }
        public short en_item_bkflopf { get; set; }
        public string en_item_lotfrmt { get; set; }
        public Nullable<double> en_item_ovtfct { get; set; }
        public short en_item_cstpltp { get; set; }
        public string en_item_procname { get; set; }
        public short en_item_qcspecf { get; set; }
        public string en_gtin_key { get; set; }
        public short en_item_cntrl { get; set; }
        public int en_item_upcnt { get; set; }
        public string en_uom_alternate { get; set; }
        public short en_item_plmf { get; set; }
        public string en_invacctgrp_key { get; set; }
        public short en_item_invcntrlf { get; set; }
        public short en_item_hazmgr { get; set; }
        public string en_item_plotfrmt { get; set; }
        public string en_item_mlotfrmt { get; set; }
    }
}
