using System;
using System.Collections.Generic;

namespace Mill_Project.Models
{
    public partial class in_whitm_tbl
    {
        public string gl_cmp_key { get; set; }
        public string in_whs_key { get; set; }
        public string in_item_key { get; set; }
        public string in_buyc_key { get; set; }
        public string in_whitm_reclc { get; set; }
        public string in_whitm_pcklc { get; set; }
        public int in_whitm_pmcd { get; set; }
        public int in_whitm_ordpl { get; set; }
        public string in_whitm_sourc { get; set; }
        public short in_whitm_leadt { get; set; }
        public short in_whitm_ndysp { get; set; }
        public double in_whitm_sstk { get; set; }
        public double in_whitm_minoq { get; set; }
        public double in_whitm_maxoq { get; set; }
        public double in_whitm_incroq { get; set; }
        public int in_whitm_ropt { get; set; }
        public double in_whitm_nqoh { get; set; }
        public double in_whitm_nnqoh { get; set; }
        public double in_whitm_alcqt { get; set; }
        public string uom_key { get; set; }
        public string in_whitm_sngrclc { get; set; }
        public string in_whitm_sngpklc { get; set; }
        public short in_whitm_shelf { get; set; }
        public int in_whitm_cmth { get; set; }
        public double in_whitm_acstext { get; set; }
        public double in_whitm_lcst { get; set; }
        public double in_whitm_pcst { get; set; }
        public double in_whitm_scst { get; set; }
        public int in_whitm_tfrtp { get; set; }
        public string gl_acct_key { get; set; }
        public string in_mohcd_key { get; set; }
        public string in_cyccd_key { get; set; }
        public Nullable<System.DateTime> in_whitm_nctdt { get; set; }
        public int in_whitm_stflg { get; set; }
        public int in_cycno_key { get; set; }
        public string in_whitm_vract { get; set; }
        public string sa_user_key { get; set; }
        public System.DateTime in_whitm_chgdt { get; set; }
        public System.DateTime in_whitm_crtdt { get; set; }
        public string en_vend_key { get; set; }
        public string ap_remt_key { get; set; }
        public string ap_delfm_key { get; set; }
        public Nullable<System.DateTime> in_cyccd_lstdt { get; set; }
        public Nullable<short> in_cyccd_freq { get; set; }
        public Nullable<System.DateTime> in_cyccd_nxtdt { get; set; }
        public Nullable<int> in_cycnt_key { get; set; }
        public Nullable<int> in_cycnt_seqno { get; set; }
        public string in_whitm_srcwhs { get; set; }
        public Nullable<short> in_whitm_ffltm { get; set; }
        public Nullable<short> in_whitm_piktm { get; set; }
        public Nullable<short> in_whitm_rsrvtm { get; set; }
        public short in_whitm_taxf { get; set; }
        public string ap_resn_key { get; set; }
        public short in_whitm_cstflg { get; set; }
        public int in_whitm_bkflinf { get; set; }
        public int in_whitm_bkflopf { get; set; }
        public short in_whitm_pdstdcstf { get; set; }
        public short in_whitm_mrkpricef { get; set; }
        public int in_whitm_advplnf { get; set; }
        public Nullable<double> in_whitm_holdcst { get; set; }
        public string en_uom_time { get; set; }
        public int in_whitm_upcnt { get; set; }
        public short in_whitm_cstpltp { get; set; }
        public short in_whitm_actcstf { get; set; }
        public string gl_acct_avgcadj { get; set; }
        public string gl_acct_icreturn { get; set; }
        public string gl_acct_icppvar { get; set; }
        public Nullable<double> in_whitm_ovtfct { get; set; }
        public string gl_acct_stkvar { get; set; }
        public string gl_acct_paccrual { get; set; }
        public double in_whitm_bmscst { get; set; }
        public double in_whitm_pmscst { get; set; }
        public double in_whitm_bmoscst { get; set; }
        public double in_whitm_pmoscst { get; set; }
        public double in_whitm_brscst { get; set; }
        public double in_whitm_prscst { get; set; }
        public double in_whitm_broscst { get; set; }
        public double in_whitm_proscst { get; set; }
        public double in_whitm_cdscst { get; set; }
        public double in_whitm_frtscst { get; set; }
        public double in_whitm_mktscst { get; set; }
        public double in_whitm_othscst { get; set; }
        public double in_whitm_bmpcst { get; set; }
        public double in_whitm_pmpcst { get; set; }
        public double in_whitm_bmopcst { get; set; }
        public double in_whitm_pmopcst { get; set; }
        public double in_whitm_brpcst { get; set; }
        public double in_whitm_prpcst { get; set; }
        public double in_whitm_bropcst { get; set; }
        public double in_whitm_propcst { get; set; }
        public double in_whitm_cdpcst { get; set; }
        public double in_whitm_frtpcst { get; set; }
        public double in_whitm_mktpcst { get; set; }
        public double in_whitm_othpcst { get; set; }
        public string in_whitm_prefpack { get; set; }
        public double in_whitm_tolunder { get; set; }
        public double in_whitm_tolover { get; set; }
        public short in_whitm_tolbasis { get; set; }
        public short in_whitm_toltype { get; set; }
        public string en_uom_tolerance { get; set; }
        public short in_whitm_pkdptlocf { get; set; }
        public short in_whitm_incusgf { get; set; }
        public string in_whitm_pprplnt { get; set; }
        public string in_whitm_abcc { get; set; }
        public Nullable<System.DateTime> in_whitm_stdrevaldt { get; set; }
        public short in_whitm_rcdptlocf { get; set; }
        public string gl_acct_contra { get; set; }
        public string gl_acct_interpo { get; set; }
        public short in_whitm_discunitf { get; set; }
        public Nullable<System.DateTime> in_whitm_stdcstexpdt { get; set; }
        public short in_whitm_autosourcef { get; set; }
        public Nullable<double> in_whitm_bklvlpercent { get; set; }
        public short in_whitm_eamflag { get; set; }
        public string in_type_key { get; set; }
        public string in_class_key { get; set; }
        public string in_comcd_key { get; set; }
        public string in_itgrp_key { get; set; }
        public string gl_invacctgrp_key { get; set; }
        public short in_whitm_invcntrlf { get; set; }
        public string in_whitm_dlotfrmt { get; set; }
        public string in_whitm_plotfrmt { get; set; }
        public string in_whitm_mlotfrmt { get; set; }
        public string en_cstcnt_rop { get; set; }
        public string en_cstcnt_plan { get; set; }
        public short in_whitm_scebackflushf { get; set; }
    }
}
