using System;
using System.Collections.Generic;

namespace Mill_Project.Models
{
    public partial class in_whitmpk_tbl_20120201
    {
        public string gl_cmp_key { get; set; }
        public string in_whs_key { get; set; }
        public string in_item_key { get; set; }
        public string im_pack_key { get; set; }
        public double in_whitmpk_acstext { get; set; }
        public double in_whitmpk_lcst { get; set; }
        public double in_whitmpk_pcst { get; set; }
        public double in_whitmpk_scst { get; set; }
        public double in_whitmpk_nqoh { get; set; }
        public double in_whitmpk_nnqoh { get; set; }
        public double in_whitmpk_alcqt { get; set; }
        public string in_whitmpk_reclc { get; set; }
        public string in_whitmpk_pcklc { get; set; }
        public double in_whitmpk_ndysp { get; set; }
        public double in_whitmpk_shelf { get; set; }
        public string in_whitmpk_sourc { get; set; }
        public int in_whitmpk_pmcd { get; set; }
        public double in_whitmpk_minoq { get; set; }
        public double in_whitmpk_maxoq { get; set; }
        public double in_whitmpk_incoq { get; set; }
        public string uom_key { get; set; }
        public string in_whitmpk_sngpklc { get; set; }
        public string in_whitmpk_sngrclc { get; set; }
        public int in_whitmpk_ordpl { get; set; }
        public double in_whitmpk_leadt { get; set; }
        public int in_whitmpk_cmth { get; set; }
        public int in_whitmpk_tftyp { get; set; }
        public double in_whitmpk_tfcst { get; set; }
        public string gl_acct_key { get; set; }
        public string in_mohcd_key { get; set; }
        public System.DateTime in_whitmpk_crtdt { get; set; }
        public System.DateTime in_whitmpk_chgdt { get; set; }
        public string in_cyccd_key { get; set; }
        public string in_stat_key { get; set; }
        public Nullable<System.DateTime> in_whitmpk_lscdt { get; set; }
        public int in_whitmpk_slmvf { get; set; }
        public string sa_user_key { get; set; }
        public int in_whitmpk_ropt { get; set; }
        public string in_whitmpk_cmnts { get; set; }
        public int in_whitmpk_upcnt { get; set; }
        public string en_vend_key { get; set; }
        public string ap_remt_key { get; set; }
        public string ap_delfm_key { get; set; }
        public double in_whitmpk_sstk { get; set; }
        public int in_whitmpk_tfrtp { get; set; }
        public Nullable<System.DateTime> in_whitmpk_nctdt { get; set; }
        public string in_whitmpk_vract { get; set; }
        public int in_cycno_key { get; set; }
        public Nullable<System.DateTime> in_cyccd_lstdt { get; set; }
        public Nullable<short> in_cyccd_freq { get; set; }
        public Nullable<System.DateTime> in_cyccd_nxtdt { get; set; }
        public Nullable<int> in_cycnt_key { get; set; }
        public Nullable<int> in_cycnt_seqno { get; set; }
        public string in_whitmpk_srcwhs { get; set; }
        public Nullable<short> in_whitmpk_ffltm { get; set; }
        public Nullable<short> in_whitmpk_piktm { get; set; }
        public Nullable<short> in_whitmpk_rsrvtm { get; set; }
        public short in_whitmpk_taxf { get; set; }
        public string ap_resn_key { get; set; }
        public short in_whitmpk_cstflg { get; set; }
        public int in_whitmpk_bkflinf { get; set; }
        public int in_whitmpk_bkflopf { get; set; }
        public int in_whitmpk_advplnf { get; set; }
        public Nullable<double> in_whitmpk_holdcst { get; set; }
        public string en_uom_time { get; set; }
        public double in_whitmpk_asinfct { get; set; }
        public short in_whitmpk_cstpltp { get; set; }
        public short in_whitmpk_actcstf { get; set; }
        public string gl_acct_avgcadj { get; set; }
        public string gl_acct_icreturn { get; set; }
        public string gl_acct_icppvar { get; set; }
        public Nullable<double> in_whitmpk_ovtfct { get; set; }
        public string gl_acct_stkvar { get; set; }
        public string gl_acct_paccrual { get; set; }
        public double in_whitmpk_bmscst { get; set; }
        public double in_whitmpk_pmscst { get; set; }
        public double in_whitmpk_bmoscst { get; set; }
        public double in_whitmpk_pmoscst { get; set; }
        public double in_whitmpk_brscst { get; set; }
        public double in_whitmpk_prscst { get; set; }
        public double in_whitmpk_broscst { get; set; }
        public double in_whitmpk_proscst { get; set; }
        public double in_whitmpk_cdscst { get; set; }
        public double in_whitmpk_frtscst { get; set; }
        public double in_whitmpk_mktscst { get; set; }
        public double in_whitmpk_othscst { get; set; }
        public double in_whitmpk_bmpcst { get; set; }
        public double in_whitmpk_pmpcst { get; set; }
        public double in_whitmpk_bmopcst { get; set; }
        public double in_whitmpk_pmopcst { get; set; }
        public double in_whitmpk_brpcst { get; set; }
        public double in_whitmpk_prpcst { get; set; }
        public double in_whitmpk_bropcst { get; set; }
        public double in_whitmpk_propcst { get; set; }
        public double in_whitmpk_cdpcst { get; set; }
        public double in_whitmpk_frtpcst { get; set; }
        public double in_whitmpk_mktpcst { get; set; }
        public double in_whitmpk_othpcst { get; set; }
        public short in_whitmpk_incusgf { get; set; }
        public string in_whitmpk_pprplnt { get; set; }
        public double in_whitmpk_tolunder { get; set; }
        public double in_whitmpk_tolover { get; set; }
        public short in_whitmpk_tolbasis { get; set; }
        public short in_whitmpk_toltype { get; set; }
        public string en_uom_tolerance { get; set; }
        public short in_whitmpk_pkdptlocf { get; set; }
        public string in_whitmpk_abcc { get; set; }
        public short in_whitmpk_rcdptlocf { get; set; }
        public Nullable<System.DateTime> in_whitmpk_stdrevaldt { get; set; }
        public Nullable<System.DateTime> in_whitmpk_stdcstexpdt { get; set; }
        public string in_type_key { get; set; }
        public string in_class_key { get; set; }
        public string in_comcd_key { get; set; }
        public string in_itgrp_key { get; set; }
        public string gl_acct_neginv { get; set; }
    }
}
