using System;
using System.Collections.Generic;

namespace Mill_Project.Models
{
    public partial class so_dtl_tbl
    {
        public string gl_cmp_key { get; set; }
        public string so_brnch_key { get; set; }
        public string so_hdr_key { get; set; }
        public short so_dtl_key { get; set; }
        public string ar_ship_key { get; set; }
        public int ar_ship_adkey { get; set; }
        public string ar_ship_adtxt { get; set; }
        public string in_prod_key { get; set; }
        public string in_prod_desc { get; set; }
        public string in_prod_uom { get; set; }
        public string pa_proj_key { get; set; }
        public string sf_work_key { get; set; }
        public string so_dtl_remks { get; set; }
        public System.DateTime so_dtl_entdt { get; set; }
        public Nullable<System.DateTime> so_dtl_clsdt { get; set; }
        public System.DateTime so_dtl_reqdt { get; set; }
        public System.DateTime so_dtl_prmdt { get; set; }
        public System.DateTime so_dtl_shsdt { get; set; }
        public Nullable<System.DateTime> so_dtl_shpdt { get; set; }
        public double so_dtl_ordqt { get; set; }
        public double so_dtl_shpqt { get; set; }
        public double so_dtl_invqt { get; set; }
        public double so_dtl_retqt { get; set; }
        public double so_dtl_totaq { get; set; }
        public double so_dtl_pikqt { get; set; }
        public double so_dtl_pkdqt { get; set; }
        public double so_dtl_costc { get; set; }
        public short so_dtl_ltaxf { get; set; }
        public int so_dtl_shply { get; set; }
        public string so_dtl_stats { get; set; }
        public int so_prod_shipf { get; set; }
        public string so_dtl_cprtn { get; set; }
        public string in_pgc_key { get; set; }
        public int so_dtl_prtsf { get; set; }
        public short so_dtl_cpoln { get; set; }
        public string so_dtl_cpono { get; set; }
        public string so_dtl_porelease { get; set; }
        public string so_dtl_lngrp { get; set; }
        public string so_dtl_shpws { get; set; }
        public string so_resn_code { get; set; }
        public string so_dtl_sltyp { get; set; }
        public Nullable<System.DateTime> so_dtl_rshdt { get; set; }
        public string so_dtl_cpshf { get; set; }
        public string so_dtl_fobds { get; set; }
        public short en_ship_fobfl { get; set; }
        public short so_dtl_holdf { get; set; }
        public int so_dtl_mstln { get; set; }
        public int so_dtl_prtpk { get; set; }
        public string po_hdr_key { get; set; }
        public short po_dtl_key { get; set; }
        public string so_dtl_pruom { get; set; }
        public short so_dtl_tolst { get; set; }
        public short so_dtl_tolsh { get; set; }
        public int so_dtl_psapf { get; set; }
        public string so_dtl_auom { get; set; }
        public double so_dtl_aordq { get; set; }
        public string sa_created_by { get; set; }
        public string sa_modified_by { get; set; }
        public System.DateTime so_dtl_chgdt { get; set; }
        public Nullable<short> so_dtl_specf { get; set; }
        public double so_dtl_ldplqt { get; set; }
        public double so_dtl_loadqt { get; set; }
        public short so_dtl_loadplf { get; set; }
        public Nullable<short> so_dtl_adjfl { get; set; }
        public Nullable<double> so_dtl_listc { get; set; }
        public string en_mode_key { get; set; }
        public string en_service_key { get; set; }
        public string en_carr_key { get; set; }
        public string en_loadpf_key { get; set; }
        public string en_frgt_key { get; set; }
        public short so_dtl_sadrf { get; set; }
        public short sa_has_extf { get; set; }
        public string so_dtl_expno { get; set; }
        public short so_dtl_s1ltf { get; set; }
        public Nullable<System.DateTime> so_dtl_cncldt { get; set; }
        public int so_dtl_upcnt { get; set; }
        public short so_dtl_tollif { get; set; }
        public short so_dtl_tolpkf { get; set; }
        public short so_dtl_tollof { get; set; }
        public int im_localgrp_key { get; set; }
        public string so_temphdr_key { get; set; }
        public string so_dtl_storeid { get; set; }
        public string so_dtl_deptno { get; set; }
        public short so_dtl_ucclreqf { get; set; }
        public short so_dtl_stradrf { get; set; }
        public Nullable<double> so_dtl_ccamt { get; set; }
        public short so_dtl_nobkordf { get; set; }
        public string gl_cmp_profit { get; set; }
        public string so_brnch_profit { get; set; }
        public string gl_cmp_ship { get; set; }
        public string so_brnch_ship { get; set; }
        public string so_dtl_shfvatregno { get; set; }
        public string so_dtl_shtvatregno { get; set; }
        public string so_dtl_exsus { get; set; }
        public short so_dtl_cnsgnf { get; set; }
        public string sf_plant_key { get; set; }
        public short so_dtl_expeditef { get; set; }
        public string so_enduse_key { get; set; }
        public string so_hdr_icsono { get; set; }
        public Nullable<short> so_dtl_csoln { get; set; }
        public Nullable<short> so_dtl_icsoln { get; set; }
        public Nullable<int> so_tempdtl_key { get; set; }
        public short so_dtl_crtprdordf { get; set; }
        public Nullable<int> so_dtl_webln { get; set; }
        public string so_dtl_invrsvid { get; set; }
        public string so_dtl_prty { get; set; }
    }
}
